global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # ── 1. Prometheus tự giám sát chính nó ──────────────────────
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # ── 2. Cụm 3 Máy Chủ Ubuntu Giám Sát Real ───────────────────
  - job_name: "ubuntu-server-01"
    static_configs:
      - targets: ["192.168.199.132:9100"]
    labels:
      server_name: "ubuntu-server-01"
      role: "web-server"

  - job_name: "ubuntu-server-02"
    static_configs:
      - targets: ["192.168.199.133:9100"]
    labels:
      server_name: "ubuntu-server-02"
      role: "db-server"

  - job_name: "ubuntu-server-03"
    static_configs:
      - targets: ["192.168.199.134:9100"]
    labels:
      server_name: "ubuntu-server-03"
      role: "app-server"
